name: dart_try
description: The Try control gives us the ability write safe code without focusing on try-catch blocks in the presence of exceptions.
version: 0.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
